version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_name}

  rabbitmq:
    image: rabbitmq:3-management
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    command: python main.py
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started

  publisher:
    build: .
    command: python publisher_main.py
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started

  consumer:
    build: .
    command: python consumer_main.py
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started
